name: el_saver
description: "EL-Saver - Your Ultimate Video Saver"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.12.0+25

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.0.10+1
  equatable: ^3.0.0
  video_player: ^2.9.5
  dartz: ^0.10.1
  path_provider: ^2.1.4
  path: ^1.9.0
  gal: ^2.3.0
  permission_handler: ^13.0.0
  get_it: ^9.2.1
  dio: ^5.5.0+1
  fluttertoast: ^10.0.0
  intl: ^0.20.2
  chewie: ^1.8.3
  adaptive_theme: ^3.6.0
  bloc: ^9.2.0
  share_plus: ^13.0.0
  device_info_plus: ^13.2.0
  firebase_core: ^4.0.0
  firebase_remote_config: ^6.0.0
  shared_preferences: ^2.2.2
  package_info_plus: ^10.2.1
  url_launcher: ^6.3.1
  open_file: ^4.0.0
  android_intent_plus: ^6.0.0
  provider: ^6.1.2
  google_mobile_ads: ^9.1.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.0
  flutter_secure_storage: ^11.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/launcher/ic_launcher_source.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/launcher/ic_launcher_source.png"
    background_color: "#121212"
    theme_color: "#7C3AED"
  windows:
    generate: true
    image_path: "assets/launcher/ic_launcher_source.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/launcher/
    - assets/splash/
    - assets/donate/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
