"""
Cookie Sync Server for ANR Saver + Cobalt
Deploy alongside Cobalt on VPS. Receives cookies from the app and writes to cookies.json.

Usage:
  pip install fastapi uvicorn
  COOKIE_PATH=/path/to/cookies.json API_KEY=your-secret-key COBALT_CONTAINER=cobalt uvicorn cookie_sync:app --host 0.0.0.0 --port 9005

Environment:
  COOKIE_PATH        - Path to Cobalt's cookies.json (default: ./cookies.json)
  API_KEY            - Secret key for authenticating requests from the app
  COBALT_CONTAINER   - Docker container name for Cobalt (for auto-restart)
"""

import json
import os
import re
import secrets as _secrets
import subprocess
import time
import uuid as _uuid
from datetime import datetime, timedelta
from pathlib import Path

from fastapi import FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(title="Cookie Sync", docs_url=None, redoc_url=None)
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

COOKIE_PATH = Path(os.getenv("COOKIE_PATH", "./cookies.json"))
API_KEY = os.getenv("API_KEY", "change-me-to-a-secret-key")
COBALT_CONTAINER = os.getenv("COBALT_CONTAINER", "cobalt")

# Premium licenses: keys.json holds {"KEY1": {"device_id": null, "redeemed_at": null}, ...}
PREMIUM_FILE = Path(os.getenv("PREMIUM_FILE", str(COOKIE_PATH.parent / "premium-licenses.json")))

# Dir for per-platform Netscape cookie files (youtube.txt, ...) read by ytdlp_api.
# Must match ytdlp_api's COOKIE_DIR so yt-dlp --cookies picks them up.
COOKIE_DIR = Path(os.getenv("COOKIE_DIR", "/opt/anrsaver/cookies"))

VALID_PLATFORMS = {
    "youtube", "instagram", "twitter",
    "facebook", "bilibili", "tiktok",
}

# yt-dlp cookie domains per platform (Netscape format needs a domain).
# YouTube Music shares youtube cookies. Public Threads extraction uses no cookies.
_COOKIE_DOMAINS = {
    "youtube": ".youtube.com",
    "instagram": ".instagram.com",
    "twitter": ".twitter.com",
    "facebook": ".facebook.com",
    # Bilibili Global/Bstation. Keep supplied keys verbatim; do not invent auth keys.
    "bilibili": ".bilibili.tv",
    "tiktok": ".tiktok.com",
}

_REQUIRED_COOKIE_KEYS = {
    "instagram": {"sessionid", "ds_user_id"},
    "facebook": {"c_user", "xs"},
}


def _cookie_pairs(cookie_str: str) -> list[tuple[str, str]]:
    pairs = []
    for part in cookie_str.split(";"):
        if "=" not in part:
            continue
        name, _, value = part.strip().partition("=")
        name = name.strip()
        if not name:
            continue
        if any(char in name or char in value for char in "\t\r\n"):
            raise ValueError("Cookie contains invalid control characters")
        pairs.append((name, value))
    return pairs


def _write_netscape(platform: str, cookie_str: str):
    """Convert 'k=v; k2=v2' to a Netscape cookies.txt for yt-dlp --cookies."""
    domain = _COOKIE_DOMAINS.get(platform)
    if not domain:
        return
    COOKIE_DIR.mkdir(parents=True, exist_ok=True)
    expiry = int(time.time()) + 60 * 60 * 24 * 365  # 1 year
    lines = ["# Netscape HTTP Cookie File", "# Generated by cookie_sync"]
    for name, value in _cookie_pairs(cookie_str):
        # domain  include_subdomains  path  secure  expiry  name  value
        lines.append(f"{domain}\tTRUE\t/\tTRUE\t{expiry}\t{name}\t{value}")
    (COOKIE_DIR / f"{platform}.txt").write_text("\n".join(lines) + "\n")


def _delete_netscape(platform: str):
    (COOKIE_DIR / f"{platform}.txt").unlink(missing_ok=True)


class CookiePayload(BaseModel):
    platform: str
    cookies: str  # "key1=val1; key2=val2; ..."


def _check_key(x_api_key: str = Header()):
    if x_api_key != API_KEY:
        raise HTTPException(401, "Invalid API key")


def _read_cookies() -> dict:
    if COOKIE_PATH.exists():
        return json.loads(COOKIE_PATH.read_text())
    return {}


def _write_cookies(data: dict):
    COOKIE_PATH.parent.mkdir(parents=True, exist_ok=True)
    COOKIE_PATH.write_text(json.dumps(data, indent=2))


def _restart_cobalt() -> bool:
    try:
        subprocess.run(
            ["docker", "restart", COBALT_CONTAINER],
            capture_output=True, timeout=30,
        )
        return True
    except Exception:
        return False


@app.post("/cookies")
def set_cookies(payload: CookiePayload, x_api_key: str = Header()):
    _check_key(x_api_key)
    if payload.platform not in VALID_PLATFORMS:
        raise HTTPException(400, f"Unknown platform: {payload.platform}")
    if not payload.cookies.strip():
        raise HTTPException(400, "Cookies cannot be empty")
    try:
        pairs = _cookie_pairs(payload.cookies)
    except ValueError as error:
        raise HTTPException(400, str(error)) from error
    names = {name for name, _ in pairs}
    missing = _REQUIRED_COOKIE_KEYS.get(payload.platform, set()) - names
    if missing:
        raise HTTPException(
            400,
            f"Missing required cookies for {payload.platform}: {', '.join(sorted(missing))}",
        )

    data = _read_cookies()
    data[payload.platform] = [payload.cookies]
    _write_cookies(data)

    # Also emit a Netscape cookies.txt so ytdlp_api can use --cookies
    _write_netscape(payload.platform, payload.cookies)

    # Auto-restart Cobalt to pick up new cookies
    restarted = _restart_cobalt()

    return {
        "status": "ok",
        "platform": payload.platform,
        "synced_at": datetime.utcnow().isoformat(),
        "cobalt_restarted": restarted,
    }


@app.get("/cookies")
def list_cookies(x_api_key: str = Header()):
    _check_key(x_api_key)
    data = _read_cookies()
    result = {}
    for p, v in data.items():
        cookie_str = v[0] if v else ""
        keys = [c.split("=")[0].strip() for c in cookie_str.split(";") if "=" in c]
        result[p] = {
            "has_cookies": bool(v),
            "cookie_count": len(keys),
            "cookie_keys": keys,
        }
    return {"platforms": result}


@app.delete("/cookies/{platform}")
def delete_cookies(platform: str, x_api_key: str = Header()):
    _check_key(x_api_key)
    data = _read_cookies()
    if platform in data:
        del data[platform]
        _write_cookies(data)
        _delete_netscape(platform)
        _restart_cobalt()
    return {"status": "ok", "platform": platform, "deleted": True}


@app.post("/restart-cobalt")
def restart_cobalt(x_api_key: str = Header()):
    _check_key(x_api_key)
    restarted = _restart_cobalt()
    return {"status": "ok", "restarted": restarted}


@app.get("/health")
def health():
    return {"status": "ok", "cookie_path": str(COOKIE_PATH), "exists": COOKIE_PATH.exists()}


# --- Premium licenses -------------------------------------------------------

LICENSE_RE = re.compile(r"^ELS-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}$")
_DEVICE_RE = re.compile(r"^[a-f0-9]{8,64}$")

# Purchase packages. days=null => perpetual.
PREMIUM_PACKAGES = {
    "monthly": {"name": "Premium 1 Bulan", "price": 5000, "days": 30},
    "yearly": {"name": "Premium 1 Tahun", "price": 15000, "days": 365},
    "lifetime": {"name": "Premium Selamanya", "price": 25000, "days": None},
}

# Manual payment instructions shown to the buyer (QRIS/DANA/WA contact).
PAYMENT_INFO = os.getenv(
    "PAYMENT_INFO",
    "Scan QRIS dengan e-wallet (GoPay/DANA/OVO) atau m-banking. "
    "Lisensi aktif otomatis setelah pembayaran terdeteksi.",
)
ADMIN_KEY = os.getenv("ADMIN_KEY", "change-admin-key")
# Static GoPay merchant QRIS payload (EMVCo) converted to dynamic per order.
STATIC_QRIS = os.getenv("STATIC_QRIS", "")
# HMAC secret for the payment webhook (auto-activation trigger).
WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET", "")

# Premium licenses: keys.json holds {"KEY1": {"device_id": null, "redeemed_at": null}, ...}
PREMIUM_FILE = Path(os.getenv("PREMIUM_FILE", str(COOKIE_PATH.parent / "premium-licenses.json")))
# Purchase orders: {order_id: {device_id, package_id, status, license, created_at, paid_at}}
ORDER_FILE = Path(os.getenv("ORDER_FILE", str(COOKIE_PATH.parent / "premium-orders.json")))


def _read_licenses() -> dict:
    if PREMIUM_FILE.exists():
        try:
            return json.loads(PREMIUM_FILE.read_text())
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def _write_licenses(data: dict):
    PREMIUM_FILE.parent.mkdir(parents=True, exist_ok=True)
    PREMIUM_FILE.write_text(json.dumps(data, indent=2))


class RedeemPayload(BaseModel):
    key: str
    device_id: str


@app.post("/premium/redeem")
def premium_redeem(payload: RedeemPayload, x_api_key: str = Header()):
    _check_key(x_api_key)
    key = payload.key.strip().upper()
    device_id = payload.device_id.strip().lower()
    if not LICENSE_RE.match(key):
        raise HTTPException(400, "Format kunci tidak valid (ELS-XXXX-XXXX-XXXX)")
    if not _DEVICE_RE.match(device_id):
        raise HTTPException(400, "device_id tidak valid")

    licenses = _read_licenses()
    entry = licenses.get(key)
    if entry is None:
        raise HTTPException(404, "Kunci tidak dikenal")
    if entry.get("device_id") and entry["device_id"] != device_id:
        raise HTTPException(409, "Kunci sudah dipakai di perangkat lain")

    entry["device_id"] = device_id
    if not entry.get("redeemed_at"):
        entry["redeemed_at"] = datetime.utcnow().isoformat()
    licenses[key] = entry
    _write_licenses(licenses)
    return {"status": "ok", "premium": True}


def _license_active(entry: dict) -> bool:
    """A license is active when bound to a device and not past expiry."""
    if not entry.get("device_id"):
        return False
    expires_at = entry.get("expires_at")
    if not expires_at:
        return True
    try:
        return datetime.fromisoformat(expires_at) > datetime.utcnow()
    except ValueError:
        return False


class VerifyPayload(BaseModel):
    device_id: str


@app.post("/premium/verify")
def premium_verify(payload: VerifyPayload, x_api_key: str = Header()):
    _check_key(x_api_key)
    device_id = payload.device_id.strip().lower()
    if not _DEVICE_RE.match(device_id):
        raise HTTPException(400, "device_id tidak valid")
    licenses = _read_licenses()
    premium = any(
        entry.get("device_id") == device_id and _license_active(entry)
        for entry in licenses.values()
    )
    return {"premium": premium}


# --- Purchase flow (auto-generated licenses, no manual key input) ----------


def _read_orders() -> dict:
    if ORDER_FILE.exists():
        try:
            return json.loads(ORDER_FILE.read_text())
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def _write_orders(data: dict):
    ORDER_FILE.parent.mkdir(parents=True, exist_ok=True)
    ORDER_FILE.write_text(json.dumps(data, indent=2))


def _generate_license(licenses: dict) -> str:
    while True:
        raw = _secrets.token_hex(6).upper()
        key = "ELS-" + "-".join(raw[i:i + 4] for i in range(0, 12, 4))
        if key not in licenses:
            return key


def _crc16(payload: str) -> str:
    """CRC-16/CCITT-FALSE as required by EMVCo QRIS (tag 63)."""
    crc = 0xFFFF
    for byte in payload.encode():
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) if crc & 0x8000 else crc << 1
            crc &= 0xFFFF
    return f"{crc:04X}"


def _tlv_parse(qris: str) -> list[tuple[str, str]]:
    out = []
    i = 0
    while i + 4 <= len(qris):
        tag = qris[i:i + 2]
        length = int(qris[i + 2:i + 4])
        out.append((tag, qris[i + 4:i + 4 + length]))
        i += 4 + length
    return out


def _tlv_build(entries: list[tuple[str, str]]) -> str:
    return "".join(f"{tag}{len(value):02d}{value}" for tag, value in entries)


def _qris_dynamic(static_qris: str, amount: str) -> str:
    """Convert a static QRIS payload to dynamic (port of
    qris-static-dynamic-core): switch to dynamic mode, inject the amount
    right after the currency tag, recompute CRC. All other tags are kept."""
    if not static_qris:
        return ""
    entries = _tlv_parse(static_qris)
    out = []
    inserted = False
    for tag, value in entries:
        if tag == "63":
            continue                      # CRC recomputed at the end
        if tag == "01":
            out.append(("01", "12"))      # point of initiation: dynamic
        elif tag == "53":
            out.append((tag, value))      # currency
            out.append(("54", amount))    # transaction amount
            inserted = True
        elif tag == "54":
            out.append(("54", amount))
            inserted = True
        else:
            out.append((tag, value))
    if not inserted:
        idx = next((i for i, (t, _) in enumerate(out) if t == "58"), len(out))
        out.insert(idx, ("54", amount))
    body = _tlv_build(out)
    return body + "6304" + _crc16(body)


def _order_amount_cents(price: int, order_id: str) -> int:
    """Unique 1-99 cent suffix so each order's gross amount is unique and a
    single payment report can be matched to exactly one order."""
    return (int(order_id[:4], 16) % 99) + 1


class OrderPayload(BaseModel):
    device_id: str
    package_id: str


@app.get("/premium/packages")
def premium_packages():
    return {
        "packages": [
            {"id": pid, **pkg} for pid, pkg in PREMIUM_PACKAGES.items()
        ]
    }


@app.post("/premium/order")
def premium_order(payload: OrderPayload, x_api_key: str = Header()):
    _check_key(x_api_key)
    device_id = payload.device_id.strip().lower()
    if not _DEVICE_RE.match(device_id):
        raise HTTPException(400, "device_id tidak valid")
    pkg = PREMIUM_PACKAGES.get(payload.package_id)
    if pkg is None:
        raise HTTPException(400, "Paket tidak dikenal")

    # Reserve a fresh license bound to this device right away.
    licenses = _read_licenses()
    license_key = _generate_license(licenses)
    licenses[license_key] = {"device_id": None, "redeemed_at": None}
    _write_licenses(licenses)

    order_id = _uuid.uuid4().hex[:16]
    cents = _order_amount_cents(pkg["price"], order_id)
    gross_amount = f"{pkg['price']}.{cents:02d}"
    qris_payload = _qris_dynamic(STATIC_QRIS, gross_amount)

    orders = _read_orders()
    orders[order_id] = {
        "device_id": device_id,
        "package_id": payload.package_id,
        "price": pkg["price"],
        "gross_amount": gross_amount,
        "status": "pending",
        "license": license_key,
        "created_at": datetime.utcnow().isoformat(),
        "paid_at": None,
    }
    _write_orders(orders)
    return {
        "order_id": order_id,
        "package_id": payload.package_id,
        "package_name": pkg["name"],
        "price": pkg["price"],
        "gross_amount": gross_amount,
        "qris": qris_payload,
        "payment_info": PAYMENT_INFO,
    }


@app.get("/premium/order/{order_id}")
def premium_order_status(order_id: str, x_api_key: str = Header()):
    _check_key(x_api_key)
    orders = _read_orders()
    order = orders.get(order_id)
    if order is None:
        raise HTTPException(404, "Order tidak ditemukan")
    result = {
        "order_id": order_id,
        "status": order["status"],
        "package_id": order["package_id"],
        "price": order["price"],
        "gross_amount": order.get("gross_amount"),
        "qris": order.get("qris"),
    }
    if order["status"] == "paid":
        # Auto-activate on this device: the app stores the key itself.
        licenses = _read_licenses()
        entry = licenses.get(order["license"], {})
        result["license_key"] = order["license"]
        result["expires_at"] = entry.get("expires_at")
    return result


class AdminConfirmPayload(BaseModel):
    admin_key: str
    order_id: str


@app.post("/premium/admin/confirm")
def premium_admin_confirm(payload: AdminConfirmPayload):
    if payload.admin_key != ADMIN_KEY:
        raise HTTPException(403, "Admin key salah")
    orders = _read_orders()
    order = orders.get(payload.order_id)
    if order is None:
        raise HTTPException(404, "Order tidak ditemukan")
    if order["status"] == "paid":
        return {"status": "ok", "already_paid": True}

    licenses = _read_licenses()
    entry = licenses.get(order["license"])
    if entry is None:
        raise HTTPException(500, "Lisensi order hilang")
    pkg = PREMIUM_PACKAGES[order["package_id"]]
    entry["device_id"] = order["device_id"]
    entry["redeemed_at"] = datetime.utcnow().isoformat()
    if pkg.get("days"):
        entry["expires_at"] = (
            datetime.utcnow().replace(microsecond=0)
            + timedelta(days=pkg["days"])
        ).isoformat()
    else:
        entry["expires_at"] = None
    licenses[order["license"]] = entry
    _write_licenses(licenses)

    order["status"] = "paid"
    order["paid_at"] = datetime.utcnow().isoformat()
    _write_orders(orders)
    return {"status": "ok", "paid": True}


class AdminListPayload(BaseModel):
    admin_key: str


@app.post("/premium/admin/orders")
def premium_admin_orders(payload: AdminListPayload):
    if payload.admin_key != ADMIN_KEY:
        raise HTTPException(403, "Admin key salah")
    orders = _read_orders()
    pending = [
        {"order_id": oid, "package_id": o["package_id"],
         "price": o["price"], "created_at": o["created_at"]}
        for oid, o in orders.items() if o["status"] == "pending"
    ]
    return {"pending": pending}


import hashlib
import hmac as _hmac


class PaymentWebhookPayload(BaseModel):
    # Matches a pending order either by id or by its unique gross amount.
    order_id: str | None = None
    gross_amount: str | None = None
    status: str = "settlement"
    signature: str  # HMAC-SHA256(order_id|gross_amount, WEBHOOK_SECRET)


@app.post("/premium/webhook")
def premium_webhook(payload: PaymentWebhookPayload):
    """Payment-notification endpoint for auto-activation. Any detection
    source (Midtrans relay, GoPay merchant watcher, manual script) posts
    here; the matching pending order is marked paid and its license
    activated. Signature: HMAC-SHA256 over 'order_id|gross_amount'."""
    if not WEBHOOK_SECRET:
        raise HTTPException(503, "Webhook belum dikonfigurasi")
    msg = f"{payload.order_id or ''}|{payload.gross_amount or ''}"
    expected = _hmac.new(
        WEBHOOK_SECRET.encode(), msg.encode(), hashlib.sha256
    ).hexdigest()
    if not _hmac.compare_digest(expected, payload.signature):
        raise HTTPException(403, "Signature tidak valid")
    if payload.status.lower() not in {"settlement", "paid", "success"}:
        return {"status": "ignored", "reason": payload.status}

    orders = _read_orders()
    order = None
    order_id = None
    if payload.order_id and payload.order_id in orders:
        order_id = payload.order_id
        order = orders[order_id]
    elif payload.gross_amount:
        for oid, o in orders.items():
            if o["status"] == "pending" and o.get("gross_amount") == payload.gross_amount:
                order_id, order = oid, o
                break
    if order is None:
        raise HTTPException(404, "Order tidak ditemukan")
    if order["status"] == "paid":
        return {"status": "ok", "already_paid": True, "order_id": order_id}

    licenses = _read_licenses()
    entry = licenses.get(order["license"])
    if entry is None:
        raise HTTPException(500, "Lisensi order hilang")
    pkg = PREMIUM_PACKAGES[order["package_id"]]
    entry["device_id"] = order["device_id"]
    entry["redeemed_at"] = datetime.utcnow().isoformat()
    if pkg.get("days"):
        entry["expires_at"] = (
            datetime.utcnow().replace(microsecond=0)
            + timedelta(days=pkg["days"])
        ).isoformat()
    else:
        entry["expires_at"] = None
    licenses[order["license"]] = entry
    _write_licenses(licenses)

    order["status"] = "paid"
    order["paid_at"] = datetime.utcnow().isoformat()
    orders[order_id] = order
    _write_orders(orders)
    return {"status": "ok", "paid": True, "order_id": order_id}
